export const COMMON = {
	CHART_COLOR: {
		RECEIVED: '#6A9D4F',
		INCOMING: '#00BAE8',
		OUTGOING: '#EC9811'
	},
	HOVER_COLOR: {
		RECEIVED: '#6A9D4F',
		INCOMING: '#00BAE8',
		OUTGOING: '#EC9811'
	}
}