export const LETTERBOARD = {
	CHART_COLOR: {
		RECEIVED: '#FF6384',
		INCOMING: '#36A2EB',
		OUTGOING: '#FFCE56'
	},
	HOVER_COLOR: {
		RECEIVED: '#FF6384',
		INCOMING: '#36A2EB',
		OUTGOING: '#FFCE56'
	}
}